### ISSUE TITLE
Merge work

### ISSUE THREAD

**Issue by ctjhoa** [jadpole/rust-book-fr#1]
Salut,
Je crois que ce que tu fais est également fait par [quelqu'un d'autre](http://blog.guillaume-gomez.fr/Rust).
À toi de voir si tu veux contribuer au projet. SInon je peux aussi te reférencer sur [rust-learning](https://github.com/ctjhoa/rust-learning) si tu pense que ton projet doit rester indépendant.

**Comment by jadpole** [comment]
De ce que j'en ai vu, il ne s'agit pas de la même chose. Ce que je fais est une traduction du livre, alors que Guillaume écrit un tutoriel complètement différent. Guillaume [partage lui-même](http://blog.guillaume-gomez.fr/Rust/1/1) un lien vers le Rust Book anglophone. On pourrait dire que les projets sont "concurrents", mais je crois plus qu'ils sont complémentaires (comme le sont le Rust Book, rust-by-example, understanding lifetimes in Rust, ...).

**Comment by ctjhoa** [comment]
@jadpole ok je t'ai référencé sur https://github.com/ctjhoa/rust-learning/blob/master/fr_FR.md

**Comment by jadpole** [comment]
@ctjhoa C'est noté.
